import type { BilingualText } from './checkInCopy'

export const BANK_COPY = {
  sectionTitle: { en: 'Business Banking', my: 'လုပ်ငန်းဘဏ်' },
  accountTitle: { en: 'Business Bank Account', my: 'လုပ်ငန်းဘဏ်အကောင့်' },
  demoBankLabel: { en: 'Thiri Fashion • Demo Bank', my: 'Thiri Fashion • Demo Bank' },
  demoConnected: { en: 'Demo Connected', my: 'သရုပ်ပြ ချိတ်ဆက်ပြီး' },
  demoConnection: { en: 'Demo Connection', my: 'သရုပ်ပြချိတ်ဆက်မှု' },
  demonstrationOnly: { en: 'Demonstration only', my: 'သရုပ်ပြသာ' },
  connectCta: { en: 'Connect Business Account', my: 'လုပ်ငန်းအကောင့် ချိတ်ဆက်ရန်' },
  connectHint: {
    en: 'Connect your business account to automatically include bank transactions in your cash-flow forecast.',
    my: 'လုပ်ငန်းအကောင့်ကို ချိတ်ဆက်ပါ။ ဘဏ်လွှဲမှုများကို ငွေလည်ပတ်မှု ခန့်မှန်းချက်တွင် အလိုအလျောက် ထည့်မည်။',
  },
  consentTitle: {
    en: 'Connect Thiri Fashion’s business account',
    my: 'Thiri Fashion ၏ လုပ်ငန်းအကောင့်ကို ချိတ်ဆက်ရန်',
  },
  consentReadBalances: { en: 'Read balances', my: 'လက်ကျန်ငွေ ဖတ်ရန်' },
  consentReadTxns: { en: 'Read transactions', my: 'ငွေလွှဲမှတ်တမ်း ဖတ်ရန်' },
  consentMatch: {
    en: 'Match sales and supplier payments',
    my: 'ရောင်းရငွေနှင့် ကုန်သည်ပေးချေမှုကို ချိတ်ဆက်ရန်',
  },
  consentForecast: { en: 'Improve forecasts', my: 'ခန့်မှန်းချက် ပိုကောင်းစေရန်' },
  consentNotRequested: {
    en: 'This demo does not request automatic transfers, automatic loan applications, or sharing private information without your consent.',
    my: 'ဤသရုပ်ပြသည် အလိုအလျောက်ငွေလွှဲခြင်း၊ အလိုအလျောက်ချေးငွေလျှောက်ခြင်း၊ သို့မဟုတ် သဘောတူချက်မရှိဘဲ ကိုယ်ရေးအချက်အလက်မျှဝေခြင်းကို မတောင်းပါ။',
  },
  connectDemo: { en: 'Connect Demo Account', my: 'သရုပ်ပြအကောင့် ချိတ်ဆက်ရန်' },
  connectedSuccess: {
    en: 'Demo account connected successfully',
    my: 'သရုပ်ပြအကောင့် ချိတ်ဆက်ပြီးပါပြီ',
  },
  openBanking: { en: 'Open Banking', my: 'ဘဏ်စာမျက်နှာဖွင့်ရန်' },
  tabAccount: { en: 'Account', my: 'အကောင့်' },
  tabPayments: { en: 'Payments', my: 'ပေးချေမှု' },
  tabReserve: { en: 'Reserve', my: 'အရန်ငွေ' },
  tabSupport: { en: 'Bank Support', my: 'ဘဏ်အကူအညီ' },
  recentTxns: { en: 'Recent transactions', my: 'လတ်တလော ငွေလွှဲများ' },
  disconnect: { en: 'Disconnect bank', my: 'ဘဏ်ဖြုတ်ရန်' },
  sharedData: { en: 'Data shared in this demo', my: 'ဤသရုပ်ပြတွင် မျှဝေသောဒေတာ' },
  copyDetails: { en: 'Copy payment details', my: 'ငွေပေးအချက်အလက် ကူးရန်' },
  generateRequest: { en: 'Generate demo payment request', my: 'သရုပ်ပြ ငွေတောင်းခံမှု ဖန်တီးရန်' },
  detailsCopied: { en: 'Payment details copied', my: 'ငွေပေးအချက်အလက် ကူးပြီး' },
  reserveHeld: { en: 'Reserve balance', my: 'အရန်လက်ကျန်' },
  reserveTarget: { en: 'Reserve target', my: 'အရန်ပစ်မှတ်' },
  reserveProgress: { en: 'Reserve progress', my: 'အရန်တိုးတက်မှု' },
  saveToReserve: { en: 'Save to Reserve', my: 'အရန်ငွေသို့ သိမ်းရန်' },
  useReserve: { en: 'Use Emergency Reserve', my: 'အရေးပေါ်စုငွေ သုံးရန်' },
  sendReminder: { en: 'Send Customer Payment Reminder', my: 'ဖောက်သည်ငွေ သတိပေးပို့ရန်' },
  receiveThroughBank: { en: 'Receive Through Bank', my: 'ဘဏ်မှ လက်ခံရန်' },
  requestSupport: { en: 'Request Bank Support', my: 'ဘဏ်အကူအညီ တောင်းရန်' },
  requestCallback: { en: 'Request a callback', my: 'ပြန်ခေါ်ရန် တောင်းဆို' },
  workingCapitalInfo: { en: 'Working-capital information', my: 'လည်ပတ်ငွေ အချက်အလက်' },
  workingCapitalBody: {
    en: 'A bank professional can discuss working-capital options if you ask. This is information only — never an automatic loan approval or credit decision.',
    my: 'သင်တောင်းမှသာ ဘဏ်ပညာရှင်က လည်ပတ်ငွေ ရွေးချယ်စရာများကို ပြောနိုင်သည်။ အချက်အလက်သာ — အလိုအလျောက်ချေးငွေခွင့်ပြုချက် သို့မဟုတ် ခရက်ဒစ်ဆုံးဖြတ်ချက် မဟုတ်ပါ။',
  },
  financialSummary: { en: 'Prepare financial summary', my: 'ငွေကြေးအနှစ်ချုပ် ပြင်ရန်' },
  summaryCopied: { en: 'Financial summary copied', my: 'ငွေကြေးအနှစ်ချုပ် ကူးပြီး' },
  predictedProblem: { en: 'Predicted cash problem', my: 'ခန့်မှန်းထားသော ငွေပြဿနာ' },
  noPredictedProblem: {
    en: 'No shortage is predicted in this view. You can still ask the bank for guidance.',
    my: 'ဤမြင်ကွင်းတွင် ငွေပြတ်မည်ဟု မခန့်မှန်းပါ။ လိုလျှင် ဘဏ်လမ်းညွှန်မှု တောင်းနိုင်သည်။',
  },
  healthyReserveHint: {
    en: 'Cash looks healthy. You can move this amount to emergency reserve.',
    my: 'ငွေသား အဆင်ပြေသည်။ ဤပမာဏကို အရေးပေါ်စုငွေသို့ ရွှေ့နိုင်သည်။',
  },
  reminderPrepared: {
    en: 'Demo reminder prepared. No money moved and no message was sent to a real customer.',
    my: 'သရုပ်ပြ သတိပေးချက် ပြင်ပြီး။ တကယ့်ငွေ မရွှေ့ပါ။ ဖောက်သည်ထံ မပို့ပါ။',
  },
  needConnection: {
    en: 'Connect the demonstration account first.',
    my: 'ဦးစွာ သရုပ်ပြအကောင့်ကို ချိတ်ဆက်ပါ။',
  },
  notLiveApi: {
    en: 'Balance is from recorded business-account movements, not a live bank API.',
    my: 'လက်ကျန်ငွေသည် မှတ်ထားသော လှုပ်ရှားမှုမှ တွက်သည်။ တိုက်ရိုက်ဘဏ် API မဟုတ်။',
  },
  status: { en: 'Connection status', my: 'ချိတ်ဆက်မှုအခြေအနေ' },
  maskedAccount: { en: 'Account', my: 'အကောင့်' },
  available: { en: 'Available business-account balance', my: 'သုံးနိုင်သော လုပ်ငန်းအကောင့်လက်ကျန်' },
  lastSync: { en: 'Last sync', my: 'နောက်ဆုံးချိတ်ဆက်' },
  neverSynced: { en: 'Not synced yet', my: 'မချိတ်ဆက်ရသေး' },
  disconnected: { en: 'Not connected', my: 'မချိတ်ဆက်ရသေး' },
  connected: { en: 'Connected', my: 'ချိတ်ဆက်ပြီး' },
  syncing: { en: 'Syncing', my: 'ချိတ်ဆက်နေသည်' },
  error: { en: 'Connection error', my: 'ချိတ်ဆက်မှုအမှား' },
  depositSales: { en: 'Deposit Today’s Sales', my: 'ယနေ့ရောင်းရငွေ အပ်နှံရန်' },
  receivePayment: { en: 'Receive Customer Payment', my: 'ဖောက်သည်ငွေ လက်ခံရန်' },
  paySupplier: { en: 'Pay Supplier', my: 'ကုန်သည်ပေးရန်' },
  moveReserve: { en: 'Move Money to Emergency Reserve', my: 'အရေးပေါ်စုငွေသို့ ရွှေ့ရန်' },
  askBank: { en: 'Ask the Bank for Support', my: 'ဘဏ်အကူအညီ တောင်းရန်' },
  reviewTitle: { en: 'Review before confirming', my: 'အတည်မပြုမီ ပြန်စစ်ပါ' },
  amount: { en: 'Amount', my: 'ပမာဏ' },
  purpose: { en: 'Purpose', my: 'ရည်ရွယ်ချက်' },
  resultingCash: { en: 'Resulting cash position', my: 'ဖြစ်လာမည့် ငွေသားအခြေအနေ' },
  cashBefore: { en: 'Cash before', my: 'မပေးမီငွေသား' },
  cashAfter: { en: 'Cash after', my: 'ပေးပြီးငွေသား' },
  confirm: { en: 'I have reviewed this. Confirm.', my: 'ပြန်စစ်ပြီး အတည်ပြုပါ' },
  confirmAction: { en: 'Confirm', my: 'အတည်ပြုရန်' },
  cancel: { en: 'Cancel', my: 'ပယ်ဖျက်ရန်' },
  close: { en: 'Close', my: 'ပိတ်ရန်' },
  neverAuto: {
    en: 'Money does not move until you confirm. This app never sends a real bank transfer.',
    my: 'အတည်မပြုမီ ငွေမရွှေ့ပါ။ တကယ့်ဘဏ်လွှဲမှု မပို့ပါ။',
  },
  selectReceivable: { en: 'Select a customer bill', my: 'ဖောက်သည်ဘီလ် ရွေးပါ' },
  selectPayable: { en: 'Select a supplier bill', my: 'ကုန်သည်ဘီလ် ရွေးပါ' },
  dueDate: { en: 'Due date', my: 'ကျရက်' },
  customer: { en: 'Customer', my: 'ဖောက်သည်' },
  reference: { en: 'Reference', my: 'ကိုးကားချက်' },
  demoQr: { en: 'Demo QR payment request', my: 'သရုပ်ပြ QR ငွေတောင်းခံမှု' },
  qrHint: {
    en: 'This QR is a demonstration request. Payment is not received until you confirm a transaction.',
    my: 'ဤ QR သည် သရုပ်ပြတောင်းခံမှုသာ။ အတည်ပြုမှသာ ငွေရသည်ဟု မှတ်သည်။',
  },
  noReceivables: { en: 'No open customer bills.', my: 'ဖွင့်ထားသော ဖောက်သည်ဘီလ် မရှိပါ။' },
  noPayables: { en: 'No open supplier bills.', my: 'ဖွင့်ထားသော ကုန်သည်ဘီလ် မရှိပါ။' },
  shortageWarn: {
    en: 'This payment would leave cash below zero.',
    my: 'ဤပေးချေမှုသည် ငွေသားကို အနုတ်ဖြစ်စေနိုင်သည်။',
  },
  reserveHint: {
    en: 'A reserve amount is suggested only when Safe to Spend is above zero. Planned is not completed.',
    my: 'သုံးရန်လုံခြုံသောငွေ ရှိမှသာ အရန်ပမာဏ အကြံပြုသည်။ စီစဉ်ခြင်းသည် ပြီးမြောက်ခြင်း မဟုတ်။',
  },
  noReserveSuggest: {
    en: 'Safe to Spend is 0, so no reserve amount is suggested. You can still type an amount.',
    my: 'သုံးရန်လုံခြုံသောငွေ ၀ ဖြစ်၍ အရန်ပမာဏ မအကြံပြုပါ။ ကိုယ်တိုင်ဖြည့်နိုင်သည်။',
  },
  stsNow: { en: 'Safe to Spend now', my: 'ယခု သုံးရန်လုံခြုံသောငွေ' },
  stsAfter: { en: 'Safe to Spend after this plan', my: 'ဤအစီအစဉ်ပြီး သုံးရန်လုံခြုံသောငွေ' },
  plannedNotDone: { en: 'Planned — not completed', my: 'စီစဉ်ထားသည် — မပြီးသေး' },
  consent: {
    en: 'I consent to share this request with the bank partner. This is not a loan application or credit check.',
    my: 'ဤတောင်းချက်ကို ဘဏ်မိတ်ဖက်သို့ မျှဝေရန် သဘောတူပါသည်။ ချေးငွေလျှောက်လွှာ သို့မဟုတ် ခရက်ဒစ်စစ်ဆေးမှု မဟုတ်ပါ။',
  },
  supportType: { en: 'Support type', my: 'အကူအညီအမျိုးအစား' },
  supportMessage: { en: 'Message for the bank (optional)', my: 'ဘဏ်သို့ မှတ်ချက် (ရှိလျှင်)' },
  shortageTitle: { en: 'If cash may run short', my: 'ငွေပြတ်နိုင်လျှင်' },
  viewBanking: { en: 'Open Banking', my: 'ဘဏ်စာမျက်နှာဖွင့်ရန်' },
  teaserTitle: { en: 'Business Bank Account', my: 'လုပ်ငန်းဘဏ်အကောင့်' },
  teaserHint: { en: 'Demo labels only. No real money moved.', my: 'နမူနာအမှတ်အသားသာ။ တကယ့်ငွေ မရွှေ့ပါ။' },
  empty: {
    en: 'No business-account movements yet. Review an action to record a demonstration.',
    my: 'လုပ်ငန်းအကောင့်လှုပ်ရှားမှု မရှိသေး။ သရုပ်ပြရန် လုပ်ဆောင်ချက်ကို ပြန်စစ်ပါ။',
  },
  loadError: { en: 'Could not load business banking', my: 'လုပ်ငန်းဘဏ်ကို မဖတ်နိုင်ပါ' },
} as const satisfies Record<string, BilingualText>
